### ISSUE TITLE
Knife Bootstrap Windows From Powershell Hangs

### ISSUE THREAD

**Issue by nhudacin** [chef/knife-windows#247]
When running a knife bootstrap windows winrm command from powershell, if any warning comes back then powershell hangs and never exits. I'd be willing to bet this isn't just specific to the knife bootstrap command. Anybody have a workaround for this? 

```
knife bootstrap windows winrm computername  -r 'role[base]' --node-name 'node-1' -x 'computername\user' -P 'password'
```

This command returns "WARNING: Switching to Negotiate authentication, Basic does not support Domain Authentication" immediately. But then nothing else. That warning appears several times before the bootstrap begins.Powershell only returns one line and then hangs indefinitely. 

I've tried: 

```powershell
cmd.exe /c "knife bootstrap windows winrm computername -r 'role[base]' --node-name 'node-1' -x 'computer\user' -P 'password'"

Start-Process "knife" -ArgumentList "bootstrap windows winrm computername -r 'role[base]' --node-name 'node-1' -x 'computer\user' -P 'password'" -NoNewWindow  -RedirectStandardOutput output.txt -RedirectStandardError error.txt -Wait

$pinfo = New-Object System.Diagnostics.ProcessStartInfo
    $pinfo.FileName = "C:\_Utilities\opscode\chefdk\bin\knife.bat"
    $pinfo.RedirectStandardError = $true
    $pinfo.RedirectStandardOutput = $true
    $pinfo.UseShellExecute = $false
    $pinfo.Arguments = "bootstrap windows winrm computername -r 'role[base]' --node-name 'node-1' -x 'computer\user' -P 'password'"
    $p = New-Object System.Diagnostics.Process
    $p.StartInfo = $pinfo
    $p.Start() | Out-Null
    $p.WaitForExit()
    $stdout = $p.StandardOutput.ReadToEnd()
    $stderr = $p.StandardError.ReadToEnd()
    Write-Host "stdout: $stdout"
    Write-Host "stderr: $stderr"
    Write-Host "exit code: " + $p.ExitCode

```

All with the same results. Running the above command from the CMD prompt works perfectly. It's like powershell is preemptively terminating based on the warning returned.

I've found this issue: https://tickets.opscode.com/browse/KNIFE-19

So far, all my other knife commands in my workflow function normally in powershell. I'm pretty sure that it's that warning causing an issue. I can probably fix the warning but the behavior is incorrect and could cause my deployment pipelines to hang if an unexpected warning occurs.

**Comment by btm** [comment]
@nhudacin could you trying running knife with -V specified twice and share the output? i.e. `knife windows bootstrap winrm 1.2.3.4 -V -V`.

Also we just released knife-windows 1.0.0.rc.0, so you could try that by installing with "gem install knife-windows --pre" Some of the winrm options are more intuitively exposed in this version. We hope to release knife windows 1.0.0 soon.

**Comment by nhudacin** [comment]
@btm absolutely!

I still can't get around this issue. Copied the command directly above to show that it's still hanging as soon as it hits the "WARNING: Switching to Negotiate authentication": The "Waiting for remote response before bootstrap." message only appears when I kill the ruby.exe process in task manager after several minutes. 

```powershell
PS C:\_SourceControl\HLGIT\build-help> $progressPreference = 'silentlyContinue';
    knife bootstrap windows winrm computername -r 'role[base]' --node-name 'node-1' -x 'computer\user' -P 'password' -V
INFO: Using configuration from C:/_SourceControl/HLGIT/build-help/.chef/knife.rb

knife : WARNING: Switching to Negotiate authentication, Basic does not support Domain Authentication
At line:2 char:5
+     knife bootstrap windows winrm computername.hostname.com -r 'role[hl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: Switch... Authentication:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Waiting for remote response before bootstrap.

PS C:\_SourceControl\HLGIT\build-help> knife windows bootstrap winrm 1.2.3.4 -V -V
knife : FATAL: Cannot find sub command for: 'windows bootstrap winrm 1.2.3.4 -V -V'
At line:1 char:1
+ knife windows bootstrap winrm 1.2.3.4 -V -V
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (FATAL: Cannot f... 1.2.3.4 -V -V':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Available windows subcommands: (for details, knife SUB-COMMAND --help)

** WINDOWS COMMANDS **
knife bootstrap windows winrm FQDN (options)
knife bootstrap windows ssh FQDN (options)
knife winrm QUERY COMMAND (options)

```

**Comment by btm** [comment]
@nhudacin I mean, `knife bootstrap windows winrm -V -V computername`

**Comment by nhudacin** [comment]
@btm thank you for all your help. I ran the gem install knife-windows --pre and noticed something unusal... That gem, along with all of the other knife-window gems did not show up in my gem list. Some how my chefDK ruby environment got all sorts of messed up.. I uninstalled everything, cleared out my gem folders (~/.chefDK & ~/.spec) and reinstalled chefDK (the latest). Everything appears to be working again. 

Closing the issue.
